name: Build & Push Frontend

on:
  push:
    branches:
      - develop # hoặc main, tùy bạn muốn CI/CD trigger khi nào

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: khadang9352/okyo-fe:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASS }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd okyo/env/prod
            docker stop okyo-fe || true
            docker rm okyo-fe || true
            docker rmi khadang9352/okyo-fe:latest || true
            docker pull khadang9352/okyo-fe:latest
            docker run -d \
              --name okyo-fe \
              -p 9091:9091 \
              khadang9352/okyo-fe:latest
